### ISSUE TITLE
fNFT APY Boost

### ISSUE THREAD

**Issue by 0xsoon** [Renaissance-DAO/renaissance-contracts#5]
**ART staking boost mechanism to let users stake their fNFTs to get higher reward rate.**

### High-level logic:
distributor -> fNFT staking distributor which maps through all the fNFTs we have and sends appropriate rebase  amounts based on their MC -> fNFT staking pool n that gives appropriate rewards

- Design Doc: https://www.notion.so/Design-fNFT-APY-Boost-49249cf846074f9e8f2a44cbf9b86cd6
- Treasury Mechanics: https://www.notion.so/Ren-Treasury-Mechanics-253dfe4cc8714eb3bf53e017548369fc

Tasks
- [ ] Create a design documentation to get the high-level overview of the implementation.
- [ ] Implement fNFT APY boosting mechanism by adding smART pool and staking contract.
- [ ] Review and Test Changes

**Comment by 0xluckyg** [comment]
moved to fnft-staking contract repo
